{"errorMessage": "[Errno 30] Read-only file system: '/root/.aws/sso/cache/becc600c205602d11d07b938dd47e2148e15bda1.json'", "errorType": "OSError", "requestId": "a9199168-5432-4c91-a0af-1598a19eae43", "stackTrace": ["  File \"/var/task/lambda_function.py\", line 26, in handler\n    _ = sns.publish_to_sns(\n", "  File \"/var/lang/lib/python3.10/site-packages/tom/common/cloud_access/aws/sns.py\", line 50, in publish_to_sns\n    return sns_client.publish(\n", "  File \"/var/runtime/botocore/client.py\", line 530, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/runtime/botocore/client.py\", line 943, in _make_api_call\n    http, parsed_response = self._make_request(\n", "  File \"/var/runtime/botocore/client.py\", line 966, in _make_request\n    return self._endpoint.make_request(operation_model, request_dict)\n", "  File \"/var/runtime/botocore/endpoint.py\", line 119, in make_request\n    return self._send_request(request_dict, operation_model)\n", "  File \"/var/runtime/botocore/endpoint.py\", line 198, in _send_request\n    request = self.create_request(request_dict, operation_model)\n", "  File \"/var/runtime/botocore/endpoint.py\", line 134, in create_request\n    self._event_emitter.emit(\n", "  File \"/var/runtime/botocore/hooks.py\", line 412, in emit\n    return self._emitter.emit(aliased_event_name, **kwargs)\n", "  File \"/var/runtime/botocore/hooks.py\", line 256, in emit\n    return self._emit(event_name, kwargs)\n", "  File \"/var/runtime/botocore/hooks.py\", line 239, in _emit\n    response = handler(**kwargs)\n", "  File \"/var/runtime/botocore/signers.py\", line 105, in handler\n    return self.sign(operation_name, request)\n", "  File \"/var/runtime/botocore/signers.py\", line 180, in sign\n    auth = self.get_auth_instance(**kwargs)\n", "  File \"/var/runtime/botocore/signers.py\", line 284, in get_auth_instance\n    frozen_credentials = self._credentials.get_frozen_credentials()\n", "  File \"/var/runtime/botocore/credentials.py\", line 610, in get_frozen_credentials\n    self._refresh()\n", "  File \"/var/runtime/botocore/credentials.py\", line 498, in _refresh\n    self._protected_refresh(is_mandatory=is_mandatory_refresh)\n", "  File \"/var/runtime/botocore/credentials.py\", line 514, in _protected_refresh\n    metadata = self._refresh_using()\n", "  File \"/var/runtime/botocore/credentials.py\", line 661, in fetch_credentials\n    return self._get_cached_credentials()\n", "  File \"/var/runtime/botocore/credentials.py\", line 671, in _get_cached_credentials\n    response = self._get_credentials()\n", "  File \"/var/runtime/botocore/credentials.py\", line 2115, in _get_credentials\n    token = initial_token_data.get_frozen_token().token\n", "  File \"/var/runtime/botocore/tokens.py\", line 82, in get_frozen_token\n    self._refresh()\n", "  File \"/var/runtime/botocore/tokens.py\", line 95, in _refresh\n    self._protected_refresh()\n", "  File \"/var/runtime/botocore/tokens.py\", line 109, in _protected_refresh\n    self._frozen_token = self._refresh_using()\n", "  File \"/var/runtime/botocore/tokens.py\", line 316, in _refresher\n    self._token_loader.save_token(\n", "  File \"/var/runtime/botocore/utils.py\", line 3090, in save_token\n    self._cache[cache_key] = token\n", "  File \"/var/runtime/botocore/utils.py\", line 3277, in __setitem__\n    os.open(full_key, os.O_WRONLY | os.O_CREAT, 0o600), 'w'\n"]}